### PR TITLE
[Cleanup] Removing merge-pull-request.py script since it is no longer used to merge PRs (see Contributor's Corner doc)

### PR DESCRIPTION
**Pull request by cameronlee314**

### CODE REVIEW

**Comment by prateekm** [comment]
@cameronlee314 Why was this removed? This is what committers (at least me) use for merging PRs.

**Comment by cameronlee314** [comment]
@prateekm I was told (by @xinyuiscool) that there was a new way to do commits: new flow is at https://cwiki.apache.org/confluence/display/SAMZA/Contributor's+Corner#Contributor'sCorner-CommitterWorkflow

**Comment by prateekm** [comment]
@cameronlee314 @xinyuiscool can we please restore the file for now. I don't see the merge button on the browser (probably need to get some access to the repo), and I'm not sure if other committers are aware of the change and have the right permissions either. The wiki is also not linked in an obvious place on the OSS site. We can remove after these are addressed

**Comment by cameronlee314** [comment]
It's fine with me to add it back. I had thought it would no longer work and that committers were already using the new way. @xinyuiscool are you ok with adding it back?

**Pull request merged**
