### PR TITLE
fix the bug containsValue method

### PR DESCRIPTION
**Pull request by jwongo**
containsValue method should invoke map.containsValue not map.containsKey

### CODE REVIEW

**Comment by guozhangwang** [comment]
LGTM. @michaelwong95 I'm not sure if Samza use github to review though, cc @nickpan47

**Comment by nickpan47** [comment]
Hi, Guozhang,

What's the context? Is there any JIRA on this one?

Samza currently is still using reviewboard for code review. We are
converting to github pull request soon.

-Yi

**Comment by nickpan47** [comment]
Nevermind, I found this pull request. I opened a JIRA to track that: https://issues.apache.org/jira/browse/SAMZA-941.

@michaelwong95 could you let me know your Apache account? We need that to assign the JIRAs.

Thanks!

**Comment by michaelwong95** [comment]
Sorry, @nickpan47 I don't have any Apache account. What is it and must I register one?

**Comment by vjagadish1989** [comment]
Apologies that this PR got missed. Merged and submitted. Looking forward to more contributions!

**Pull request closed without merging**
