### PR TITLE
SAMZA-2674: Change StorageEngine and KeyValueStore init call parameters

### PR DESCRIPTION
**Pull request by dxichen**
Update the StorageEngine and KeyValueStore apis to only use Context parameter for custom store types
@Sanil15 @prateekm

### CODE REVIEW

**Review by prateekm — APPROVED** [review]
Change looks good to me, thanks for the cleanup. Can you check the build failure?
Let's update PR description and have @Sanil15 take a look as well.

**Comment by dxichen** [comment]
The build failure seems to be caused by a library being deprecated, updated it here: https://github.com/apache/samza/pull/1522

**Comment by Sanil15** [comment]
> Update the StorageEngine and KeyValueStore apis to only use Context parameter for custom store types

@dxichen please ensure wrapped store init is invoked and not raw store, else LGTM

**Comment by dxichen** [comment]
> @dxichen please ensure wrapped store init is invoked and not raw store in the new lifecycle, else LGTM

@Sanil15 yep, it is evoking wrapped store and not raw store directly

**Pull request merged**
