### PR TITLE
SAMZA-2616: Upgrade ZK Client.

### PR DESCRIPTION
**Pull request by perkss**
**Issues:** The current ZK Client versions are very old and contain security risks and bugs that have been fixed with newer versions of the libraries Samza uses. The current ZKClient library we use stops at 0.11 therefore any newer version of Zookeeper is a much bigger change. This upgrades to the latest version to improve Samza with minimal disruption.
 
**Changes:** Describe major changes, listing each separately.
    1. Upgrade Zookeeper version 3.4.13
    2. Upgrade ZKClient version to 0.11
 
**Tests:** Run the check-all tests. 
**API Changes:** None
**Upgrade Instructions:** None
**Usage Instructions:** None

### CODE REVIEW

**Comment by mynameborat** [comment]
@perkss Thanks for picking this up and contributing to Samza.
Can you please follow the PR guidelines outlined [here](https://cwiki.apache.org/confluence/display/SAMZA/SEP-25%3A+PR+Title+And+Description+Guidelines) and update the description?

**Comment by perkss** [comment]
@mynameborat thanks for the pointers. Will the travis job kick in? Was hoping to run it on the tests take a long time to run locally.

**Comment by nickpan47** [comment]
@perkss not sure why the Travis build stuck at queueing stage. I have manually resubmit the build and let's see whether it actually started.

**Comment by mynameborat** [comment]
> @perkss not sure why the Travis build stuck at queueing stage. I have manually resubmit the build and let's see whether it actually started.

@nickpan47 I tried restarting it couple of times as well. It either seems to get stuck in submission or queuing.

**Comment by perkss** [comment]
@nickpan47 @mynameborat build is all green now.

**Comment by mynameborat** [comment]
> @nickpan47 @mynameborat build is all green now.

Thanks for triggering one more build. Merged the PR

**Review by mynameborat — APPROVED** [review]

**Pull request merged**
