### PR TITLE
SAMZA-1048 : upgrade jetty dependency to Jetty 9 from Jetty 8

### PR DESCRIPTION
**Pull request by fredji97**
Jetty 8 is a very old jetty version and the current widely used version is Jetty 9. If a user is using standalone Samza in a Jetty container, and he/she is using Jetty 9, he/she may see some incompatibility issue and it makes a lot of sense for a user to upgrade the Jetty version on his/her side instead of downgrading the Jetty version.

### CODE REVIEW

**Review by vjagadish1989 — APPROVED** [review]
approved, thanks Fred for the contribution.

feedback from final round of review: Presumably, the method `getLocalPort` is available only in NetworkConnector?

**Comment by nickpan47** [comment]
lgtm. Note: there seems to be a merging conflict. Please resolve it before commit.

**Comment by fredji97** [comment]
@vjagadish1989, yes, getLocalPort is not available in the superinterface Connector but is available in the the subinterface NetworkConnector.

@nickpan47 Thanks. I have resolved the confilct.

**Comment by nickpan47** [comment]
👍

**Pull request closed without merging**
