### PR TITLE
Misc. Util cleanup

### PR DESCRIPTION
**Pull request by prateekm**
Major changes:
1. Broke up 'Util' class into multiple classes: 'FileUtil', 'HttpUtil', 'CoordinatorStreamUtil'.
2. Consolidated some Util classes: MathUtil, ScalaJavaUtil
3. Removed redundant Util classes: ClassloaderUtil, ScalaToJavaUtil
4. Renamed some Util classes for consistency: TimerUtils -> TimerUtil.
5. Inlined some util classes and methods to where they're used: LexicographicComparator to RocksDBKeyValueStore, defaultSerdeFactoryFromSerdeName to SerdeManager, etc.

Rest of the changes are updates to use the new classes and methods.

Testing: Local build and test works. Tested with a locally deployed Samza job.

### CODE REVIEW

**Comment by prateekm** [comment]
@vjagadish1989 @jmakes

**Comment by prateekm** [comment]
FYI @xinyuiscool @sborya @nickpan47.

**Comment by nickpan47** [comment]
@prateekm thanks for the patch. Just noticed that there is a conflict with master now. Could you help to update this patch against the master? Thanks!

**Comment by prateekm** [comment]
@nickpan47 rebased from master. Will commit by EOD if everything looks good.

**Pull request closed without merging**
