### PR TITLE
SAMZA-1915: Added docs for table API

### PR DESCRIPTION
**Pull request by weisong44**
As per subject

### CODE REVIEW

**Comment by vjagadish1989** [comment]
In the "API" menu on the left, Can you add a "Table API" anchor that links to your page?

**Comment by vjagadish1989** [comment]
also like @cameronlee314 did for PR: https://github.com/apache/samza/pull/663 can you attach a screenshot of how it renders on the website?

**Comment by weisong44** [comment]
> In the "API" menu on the left, Can you add a "Table API" anchor that links to your page?
This PR includes changes in documentation/versioned/index.html, did you mean somewhere else?

**Comment by weisong44** [comment]
table-api-screenshot

**Comment by vjagadish1989** [comment]
@weisong44 : Looks like there are some merge conflicts? Can you fix it too? otherwise, looks good to merge

**Pull request closed without merging**
