### PR TITLE
SAMZA-1307 - Fix ZkKeyBuilder null checks for pathPrefix

### PR DESCRIPTION
**Pull request by navina**

### CODE REVIEW

**Review by vjagadish1989 — APPROVED** [review]
approved. proposed changes look good to me.

**Comment by navina** [comment]
@vjagadish1989 That was fast ! 👍

**Comment by shanthoosh** [comment]
Invocation of ZkKeyBuilder.parseIdFromPath(currentPath) from ZkLeaderElector.tryBecomeLeader will cause similar NPE. 

If it makes sense we can fix that too.

**Comment by navina** [comment]
@shanthoosh I already merged this PR. Let me re-open the jira and provide another PR for this. Thanks for bringing it up.

**Pull request closed without merging**
