### PR TITLE
SAMZA-1274: Update kafka-python and kafka broker version for integration tests

### PR DESCRIPTION
**Pull request by prateekm**

### CODE REVIEW

**Comment by prateekm** [comment]
@xinyuiscool can you please merge this. Thanks!

**Review by vjagadish1989 — APPROVED** [review]
approved. looks good to me. thanks Prateek for the contribution!

**Comment by vjagadish1989** [comment]
@fredji97 : The version of Kafka client that we use is newer than the version of Kafka broker. In general, there are no compatibility guarantees between newer versions of clients and older versions of brokers.

**Comment by vjagadish1989** [comment]
Merged, and submitted. Thanks for fixing this @prateekm!

**Pull request closed without merging**
