### PR TITLE
SAMZA-1293: Enable partition expansion of input streams (SEP-5)

### PR DESCRIPTION
**Pull request by lindong28**

### CODE REVIEW

**Comment by vjagadish1989** [comment]
@lindong28 : Perhaps I missed the discussion on the SEP. Can we please send out a [DISCUSS] email to open source?

**Comment by lindong28** [comment]
@vjagadish1989 Thanks for the reminder. The KIP is still work-in-progress and it can be found at https://cwiki.apache.org/confluence/display/SAMZA/SEP-5%3A+Enable+partition+expansion+of+input+streams. I am still working on the proposed change section for "Handle partition expansion while tasks are running". I will send out the DISCUSS email after the KIP is completed. I have opened this pull request for ease of preliminary review and discussion.

**Comment by navina** [comment]
@lindong28  I would question the motivation for this PR or even SEP, when there has been no discussion around it. Since I don't have any context, I am more inclined towards a -1 for this PR. 

It is difficult for Samza community and developers to review your changes without any context. Please start a discussion in the mailing list so that everyone is on the same page and we can make progress.

**Comment by lindong28** [comment]
@navina This pull request is ready for official so there is no need for something official such as +1 or -1. I will start discussion thread when the SEP is ready.

**Comment by lindong28** [comment]
We will re-open pull request after SEP-5 discussion.

**Pull request closed without merging**
