### PR TITLE
Samza docs for YARN deployments

### PR DESCRIPTION
**Pull request by abhishekshivanna**

### CODE REVIEW

**Comment by vjagadish1989** [comment]
fix merge conflicts, and move yarn section to the "deployments/" directory?

**Review by vjagadish1989 — APPROVED** [review]
Approved; thanks @abhishekshivanna. can you also attach some screenshots of how it renders?

**Comment by abhishekshivanna** [comment]
screencapture

**Comment by vjagadish1989** [comment]
merged and submitted! Looks great!

**Pull request closed without merging**
