### PR TITLE
Merge script improvement - use colons instead of semicolons

### PR DESCRIPTION
**Pull request by jmakes**

### CODE REVIEW

**Comment by jmakes** [comment]
Hey committers, what say you?
Our convention seems to be colons. How about we make it Python official?
@xinyuiscool @nickpan47 @vjagadish1989 @sborya @prateekm

**Review by vjagadish1989 — APPROVED** [review]
approved, looks good to me

**Comment by vjagadish1989** [comment]
Would also be nice to do the same for our hello-samza merge script too consistently.

**Comment by jmakes** [comment]
@vjagadish1989 this was already done on the hello-samza merge script at the same time the script was added to that repo. 
In fact, this PR was created by diff'ing the 2 scripts. :-)

**Pull request closed without merging**
