### PR TITLE
SAMZA-2361: Revert "Samza-2330: Handle expired resource request for Container allocator when host affinity is disabled"

### PR DESCRIPTION
**Pull request by Sanil15**
**Symptom:** PR #1170 introduced expired request checking for Host Affinity disabled cases, however, this leads to a few problems that we might face in future:
1. In the scenarios of a cluster bounce, this might result in jobs (in either case of host affinity enabled & disabled cases) requesting containers from the ClusterResourceManager every 5 (default request expiry timeout) seconds if requests can't be fulfilled. Before PR #1170 this only used to happen for host affinity disabled jobs. This might potentially result in bringing down the ClusterManager. 
2. Unless we have some performance benchmarking on RM (for Yarn as a cluster balancer), having a default expiry timeout of 5 seconds for all container requests is not justified.

**Cause:** PR #1170

**Fix:** We are reverting this behavior change since we don't have Performance benchmarking for Yarn

**Tests:** Refactored test to ensure, expired requests are only checked with host affinity enabled jobs

**API Changes:** N/A

**Upgrade Instructions:** N/A

### CODE REVIEW

**Comment by Sanil15** [comment]
@rmatharu please have a look!

**Comment by prateekm** [comment]
@Sanil15 Is this a revert of a previous commit? If so, instead of reverting on master, you should revert the commit on the release branch. @lhaiesp can help you with that.

**Comment by Sanil15** [comment]
@prateekm let's revert it on master too since before enabling this behavior we need more benchmarking, after that we can cherry-pick this change to release branches?

**Comment by prateekm** [comment]
Sure, revert it from both master and the 1.3 branch in that case.

**Pull request merged**
