### PR TITLE
SAMZA-2669: Inject MetricsRegistry into SamzaContainer so that it can be shared in higher layers

### PR DESCRIPTION
**Pull request by cameronlee314**
Issues: `SamzaContainer` currently creates its own `MetricsRegistryMap` inside of its `apply` method. This means any layers that use `SamzaContainer` are unable to share this `MetricsRegistry`. There will be an upcoming PR which wraps `SamzaContainer` into another layer, and it needs access to the metrics object.

Changes:
1. Inject a `MetricsRegistryMap` as an argument into `SamzaContainer.apply`
2. Remove unused `name` field from `MetricsRegistryMap`.

Tests:
`./gradlew build`

API changes and upgrade/usage instructions: `MetricsRegistryMap` no longer has a "name" associated with it. There is no longer a constructor for `MetricsRegistryMap` which accepts a `name`, and `MetricsRegistryMap` no longer has a `getName` method. Since `MetricsRegistryMap` is in `samza-core`, this is not a public API, but putting a note here just in case.

### CODE REVIEW

**Comment by mynameborat** [comment]
I remember something about the `MetricsSnapshotReporter` being instantiated within the `SamzaContainer` as well. Any plans to inject that as well from the higher layers e.g., `ContainerLaunchUtil` so that other components within can reuse the reporters?

I think the change itself was not huge from the perspective of YARN although it had few considerations on the standalone front due to difference in lifecycle between `SamzaContainer` & `StreamProcessor`

**Comment by cameronlee314** [comment]
> I remember something about the `MetricsSnapshotReporter` being instantiated within the `SamzaContainer` as well. Any plans to inject that as well from the higher layers e.g., `ContainerLaunchUtil` so that other components within can reuse the reporters?
> 
> I think the change itself was not huge from the perspective of YARN although it had few considerations on the standalone front due to difference in lifecycle between `SamzaContainer` & `StreamProcessor`

IMO, the way that Samza handles metrics in general is not very clean right now, and the refactoring needed to really clean it up is a bigger scope. There isn't very good dependency injection, so there isn't a single spot where metrics all get hooked up, so different components do their own reporter registration. Also, the reporters need to get started in some deep layer (e.g. `ContainerProcessManager` or `SamzaContainer.run`) because the registries need to be registered before starting the reporters (`MetricsReporter` doesn't define the contract about the ordering of registers/start, and at least I see one `MetricsReporter` implementation that assumes everything is registered first).
Therefore, I was just trying to do a more minimal change for now to get what I needed. Injecting the full set of reporters into `SamzaContainer` would clean up the code, but wouldn't add much more capability because `SamzaContainer` already registers all of the reporters with the registry that is now passed in.
Do you think this change itself is reasonable to put it on its own or do you think we should include some more clean up with it?

**Comment by mynameborat** [comment]
> > I remember something about the `MetricsSnapshotReporter` being instantiated within the `SamzaContainer` as well. Any plans to inject that as well from the higher layers e.g., `ContainerLaunchUtil` so that other components within can reuse the reporters?
> > I think the change itself was not huge from the perspective of YARN although it had few considerations on the standalone front due to difference in lifecycle between `SamzaContainer` & `StreamProcessor`
> 
> IMO, the way that Samza handles metrics in general is not very clean right now, and the refactoring needed to really clean it up is a bigger scope. There isn't very good dependency injection, so there isn't a single spot where metrics all get hooked up, so different components do their own reporter registration. Also, the reporters need to get started in some deep layer (e.g. `ContainerProcessManager` or `SamzaContainer.run`) because the registries need to be registered before starting the reporters (`MetricsReporter` doesn't define the contract about the ordering of registers/start, and at least I see one `MetricsReporter` implementation that assumes everything is registered first).
> Therefore, I was just trying to do a more minimal change for now to get what I needed. Injecting the full set of reporters into `SamzaContainer` would clean up the code, but wouldn't add much more capability because `SamzaContainer` already registers all of the reporters with the registry that is now passed in.
> Do you think this change itself is reasonable to put it on its own or do you think we should include some more clean up with it?

Fair enough. Appreciate the context and background. I recollect some of these issues during my testing to refactor metrics reporter DI. Given you have deeper, fresh context on this, can you please collect all your context and ideas on this and create a ticket when possible.

As far as this PR, I think it is fine to get this checked in.

**Review by mynameborat — APPROVED** [review]
Even though its in samza-core, I hope there isn't any extenders or usages of MetricsRegistryMap that uses this `name` field. 

Might be useful to just add that API changes in the description so that folks know this is breaking.

**Pull request merged**
