### PR TITLE
SAMZA-2556:AzureBlob SystemProducer: Fix NPE thrown during flush. NPE caused by unhandled previous exceptions

### PR DESCRIPTION
**Pull request by lakshmi-manasa-g**
**Bug fix**
**Symptom:**  NPE thrown during SystemProducer.flush if AzureBlobAvroWriter earlier threw an IllegalStateException.

**Cause:** First message passed into AzureBlobAvroWriter is a bad record without schema then the avro objects are not created due to IllegalStateException. However, if the user of the system producer still invokes a flush (either directly or through stop), NPE is thrown as flush of producer invokes flush of the writer which inturn accesses the non-existent avro objects.

**Changes:** check if the avro components are not null before accessing.

API changes: None

Upgrade Instructions: None

Usage Instructions: None

Tests: existing tests pass

### CODE REVIEW

**Comment by mynameborat** [comment]
why does flush get invoked again if the previous exception was unhandled?
Does the upstream swallow the exception and continue in degraded mode and subsequently invokes flush again?

**Comment by lakshmi-manasa-g** [comment]
yes, that is exactly the case.
the upstream decided to invoke flush on the AzureBlobSystemProducer which inturn invokes flush on all the writers registered with it. The reason for upstream to do so is to commit all the blobs in-flight right now with other writers.

**Comment by mynameborat** [comment]
> yes, that is exactly the case.
> the upstream decided to invoke flush on the AzureBlobSystemProducer which inturn invokes flush on all the writers registered with it. The reason for upstream to do so is to commit all the blobs in-flight right now with other writers.

1. Are there other places that might need same handling or is it only the flush method that gets invoked after an uncaught exception? 
2. Would be good if we can rely on explicit signal instead of null being the signal for uncaught exception.
By having an explicit signal, you can enforce the invariant on flush not getting invoked only in the case of unhandled exception but not in other scenarios where the field got nulled. 
3. Can we have a unit test for this scenario?

**Comment by lakshmi-manasa-g** [comment]
Answers inline

> 1. Are there other places that might need same handling or is it only the flush method that gets invoked after an uncaught exception?

The AzureBlobSystemProducer has only these operations : start, send, flush and stop. If there is an exception caught in send then flush and/or stop could be called. Both of these operations call flush on the underlying AzureBlobAvroWriter. Hence it would be only in writer.flush that this problem of NPE can occur. Besides the writer.write operation invoked from the send of the producer is already chcking for currentBlobWriterComponents being null. Hence this null check in flush is only other place.


>2. Would be good if we can rely on explicit signal instead of null being the signal for uncaught exception.
>By having an explicit signal, you can enforce the invariant on flush not getting invoked only in the case of unhandled exception but not in other scenarios where the field got nulled.

CurrentBlobWriterComponents is null when the writer is created and remains null until the first message is successfully (correct schema, encoding .. ) written. After the first message CurrentBlobWriterComponents is non null. 
However, if first message write failed then this is null and an explicit signal (if added) will also be false. Thus i feel an explicit signal will be equivalent to this null check. 
Added a isClosed check along with null check as writer.flush should not be called after writer.close. This does NOT cause scenario for the current NPE.. just securing and adhering to the writer interface expectations.

>3. Can we have a unit test for this scenario?

added.

**Pull request merged**
