### PR TITLE
emit to diagnostic kafka topic in round robin fashion to support increasing this topic partition count

### PR DESCRIPTION
**Pull request by jia-gao**
Symptom: For some Samza jobs, the size of the diagnostic stream partition grows to be large and can cause issues in system streams like Kafka

Cause:
Currently, diagnostics topics for Samza jobs are created with a single partition. 
Because it is created in DiagnosticsUtil and uses the default partition count, which is 1.
There could be a need to increase the partition count of the diagnostic stream to resolve the issue above. 
However, Samza currently uses hostnames as partition key to distribute diagnostic msgs.  The host names can be very similar, the hash of these in the partition key will not evenly distribute the msgs across partitions.

Change: 
Use the “null” partition key instead of using the hostname as the partition key, and leverage on  Kafka default partitioner to evenly distributed the events across partitions.
Note that this change is backward compatible with the default partition count (1) since every msg goes to the same partition regardless of the partition key.

API changes: None

Backward compatible: No. Note that the change will be backwards incompatible only when the diagnostic stream has more than one partition. The default creation for diagnostic stream inside samza is with 1 partition, but there are cases that the stream pre-exists or partition count increased after creation.

Test Done:
./gradlew build

### CODE REVIEW

**Comment by jia-gao** [comment]
> lets please follow https://cwiki.apache.org/confluence/display/SAMZA/SEP-25%3A+PR+Title+And+Description+Guidelines for all samza PR descriptions
> 
> We also need to explain that for open source samza, the partition count is 1 for diagnostics stream due to DiagnosticsUtil.createDiagnosticsStream which relies on default parttition count within stream spec which is set to 1. hence this change will not break anything for open source community and is backwards compatible. However, it allows for better distrubution if the diag topic's partition count is increased and some info on how null partition key helps for the most commonly used system aka kafka.

Thanks, updated

**Review by lakshmi-manasa-g — APPROVED** [review]
lgtm

**Comment by mynameborat** [comment]
Is the partition key field not used as part of the emitted payload in downstream? That does seem like a backward incompatible change given the messages produced going forward wouldn't have the hostname exposed as key of the message?

**Comment by lakshmi-manasa-g** [comment]
> Is the partition key field not used as part of the emitted payload in downstream? That does seem like a backward incompatible change given the messages produced going forward wouldn't have the hostname exposed as key of the message?

partition key field is used to determine which partition of the diagnostics stream to send the message to right. partition key is not part of the payload itself the payload for these messages is MetricsSnapshotSerdeV2().toBytes(diagnosticsStreamMessage.convertToMetricsSnapshot. 
the most commonly used diagnostics system aka kafka for uses partition key for routing the msg key (which is null here) and msg value (which is the metrics snapshot) pair to the appropriate partition. partition key does not become the msg key right, msg key is explicitly set to null here.

given that diagnostic stream is created with 1 partition count by default, this change will be backwards compatible right.

did you mean the case where partition count is set to larger than 1 then this is not backwards compatible?

**Comment by mynameborat** [comment]
> 

Just noticed the constructor this is the partition key and not the message key. It should be okay from that front. In terms of the assumption on diagnostics stream is stream with one partition count, can that be created explicitly by the user? Or potentially expanded to more than one partition?

In that case, it could still mean a incompatible change right?

**Comment by jia-gao** [comment]
> > In terms of the assumption on diagnostics stream is stream with one partition count, can that be created explicitly by the user? Or potentially expanded to more than one partition?
> > In that case, it could still mean a incompatible change right?
> 
> the default creation for diag stream inside samza framework code is with 1 partition. that said, i think it can be expanded to more than 1 partition. Maybe if the stream is pre-created before the job creates it then it can be created with >1 as well. Yes, if the diag stream has >1 partition prior to upgrading to this PR, then it could be an incompatible change. thanks for catching this.
> 
> @jia-gao can you please mark this PR as backwards incompatible along with an explanation as to WHEN it is backwards incompatible. without the when part, this might be seen as a breaking change in all cases which it is not.

make sense, updated the description

**Pull request merged**
