### PR TITLE
SAMZA-2533: Fix DiagnosticsUtil to use configured MetricsReporterFactory

### PR DESCRIPTION
**Pull request by abhishekshivanna**
DiagnosticsUtil#buildDiagnosticsManager currently hard codes
the creation of MetricsSnapshotReporter.
This patch fixes this and creates the MetricsReporter
using the factory defined in configs.

Edit (06/01): This patch also changes `DiagnosticsUtil#buildDiagnosticsManager` to use two separate producers for the MetricsSnapshortReporter and `DiagnotsticsManager`.

### CODE REVIEW

**Comment by abhishekshivanna** [comment]
Please note: `MetricsSnapshotReporter#getProducer` will be removed once https://github.com/apache/samza/pull/1368 is merged.

**Comment by xiefan46** [comment]
lgtm.

**Comment by rmatharu** [comment]
Perhaps adding a test in TestDiagnosticsManager would be prudent?

**Comment by abhishekshivanna** [comment]
> Perhaps adding a test in TestDiagnosticsManager would be prudent?

This patch doesn't change the DiagnoticsManager (hence nothing to change in TestDiagnosticsManager ??). Instead, I added a test to verify that the reporter created (using `DiagnosticsUtil#buildDiagnosticsManager`) comes from the factory in configs.
Let me know if this looks good.

**Comment by abhishekshivanna** [comment]
Based on comments received on https://github.com/apache/samza/pull/1368. This patch removes exposing the producer in `MetricsSnapshotReporter`. 
Rather, instantiates two separate producers for `DiagnotsticsManager` and `MetricsSnapshotReporter`

**Pull request merged**
